"""empty message

Revision ID: 2520d621bb08
Revises: 176a7130ff30
Create Date: 2023-02-21 14:35:48.440734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2520d621bb08'
down_revision = '176a7130ff30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Favorite', sa.Column('history_no', sa.Integer(), nullable=True, comment='히스토리 번호'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Favorite', 'history_no')
    # ### end Alembic commands ###
