"""empty message

Revision ID: 35d2bf01cc4f
Revises: a2b5b6f70208
Create Date: 2023-02-22 11:32:30.613896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d2bf01cc4f'
down_revision = 'a2b5b6f70208'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Favorite', sa.Column('history_content_lang', sa.String(length=50), nullable=True, comment='즐겨찾기 내용 언어'))
    op.add_column('Favorite', sa.Column('history_content_result_lang', sa.String(length=50), nullable=True, comment='즐겨찾기 번역 언어'))
    op.add_column('History', sa.Column('history_content_lang', sa.String(length=50), nullable=True, comment='히스토리 내용 언어'))
    op.add_column('History', sa.Column('history_content_result_lang', sa.String(length=50), nullable=True, comment='히스토리 번역 언어'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('History', 'history_content_result_lang')
    op.drop_column('History', 'history_content_lang')
    op.drop_column('Favorite', 'history_content_result_lang')
    op.drop_column('Favorite', 'history_content_lang')
    # ### end Alembic commands ###
