"""empty message

Revision ID: 665a8fa5e70d
Revises: 8048f0dbb808
Create Date: 2023-03-01 01:57:41.892370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665a8fa5e70d'
down_revision = '8048f0dbb808'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
