"""empty message

Revision ID: 720020b23e25
Revises: 04560261df43
Create Date: 2023-02-27 13:12:06.594161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720020b23e25'
down_revision = '04560261df43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
