"""empty message

Revision ID: 8048f0dbb808
Revises: 3a1cc08e2840
Create Date: 2023-02-28 13:20:50.190529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8048f0dbb808'
down_revision = '3a1cc08e2840'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EmailNumber',
    sa.Column('user_email', sa.String(length=50), nullable=False, comment='사용자 이메일(ID)'),
    sa.Column('user_name', sa.String(length=50), nullable=True, comment='사용자 이름'),
    sa.Column('vnum', sa.Integer(), nullable=True, comment='인증 번호'),
    sa.Column('expire_time', sa.DateTime(), nullable=True, comment='만료시간'),
    sa.PrimaryKeyConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EmailNumber')
    # ### end Alembic commands ###
