"""empty message

Revision ID: 8ec14bb81ae1
Revises: efce57ec7343
Create Date: 2023-02-21 13:25:43.787988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec14bb81ae1'
down_revision = 'efce57ec7343'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('History', sa.Column('history_content_result', sa.Text(), nullable=True, comment='히스토리 번역 결과'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('History', 'history_content_result')
    # ### end Alembic commands ###
