"""empty message

Revision ID: a2b5b6f70208
Revises: 2520d621bb08
Create Date: 2023-02-22 09:16:17.170295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b5b6f70208'
down_revision = '2520d621bb08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
