"""empty message

Revision ID: f6124487565a
Revises: 17de5dd7428c
Create Date: 2023-02-15 10:59:51.240371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6124487565a'
down_revision = '17de5dd7428c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_no', sa.Integer(), autoincrement=True, nullable=False, comment='사용자 번호'),
    sa.Column('user_email', sa.String(length=50), nullable=True, comment='사용자 이메일(ID)'),
    sa.Column('user_name', sa.String(length=50), nullable=True, comment='사용자 이름'),
    sa.Column('user_nick', sa.String(length=50), nullable=True, comment='사용자 닉네임'),
    sa.Column('user_pwd', sa.String(length=50), nullable=True, comment='사용자 비밀번호'),
    sa.Column('user_create_date', sa.DateTime(), nullable=True, comment='가입날짜'),
    sa.Column('user_image', sa.String(length=500), nullable=True, comment='사용자 이미지'),
    sa.PrimaryKeyConstraint('user_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
